### ISSUE TITLE
Not adding segment?

### ISSUE THREAD

**Issue by EthanG45** [danielnehrig/iTerm2segments#3]
I ran the install script, and I'm not seeing the segment for iTunes nor Spotify appearing in the status bar segment editor.

**Comment by danielnehrig** [comment]
have you followed the readme instruction ?

**Comment by EthanG45** [comment]
@danielnehrig  I ran the `install.py` script and it seemingly succeeded creating the directories it needed. My understanding was the segment would appear in this area of the settings, but it's not here
<img width="899" alt="image" src="https://user-images.githubusercontent.com/55003415/131966059-16468f9e-4398-42dc-968f-9d132f7415b6.png">

**Comment by EthanG45** [comment]
@danielnehrig I realize now the issue was not understanding the need to go under the scripts menu. #4 helped me realize this. Also I will note that on first install your script does seem to error out and require a restart of iTerm 2 though 
<img width="269" alt="image" src="https://user-images.githubusercontent.com/55003415/132108689-460938a5-2d5b-4008-a962-94419687299f.png">

Edit: the script seems to break whenever you leave the iTerm 2 windows as well. In general CPU usage seems much higher while running the script too.

**Comment by danielnehrig** [comment]
thanks for the info and i'm glad you could figure out your problem
i'm not using iterm2 anymore for quite some time so things might have changed or broken here and there

feel free to optimize it and submit a pr
